### ISSUE TITLE
Support setting up SSH key from AWS secret manager

### ISSUE THREAD

**Issue by scriptnull** [hasura/smooth-secrets-buildkite-plugin#1]
We will aim for a format like this

```yaml
  - label: "Test secret"
    plugins:
      - hasura/smooth-secrets#v1.0.0:
          secrets:
            - strategy: aws-secret-manager
              key: github-deploy-keys/repo-name
              type: ssh
              region: us-east-2
    command: ls
```
