### ISSUE TITLE
Support env secrets strategy

### ISSUE THREAD

**Issue by scriptnull** [hasura/smooth-secrets-buildkite-plugin#3]
```yml
            - strategy: aws-secrets-manager
              key: hasura/cred
              type: env # pre_command hook
              name: NAME_OF_SECRET
              region: us-east-2
```
