### ISSUE TITLE
support file strategy

### ISSUE THREAD

**Issue by scriptnull** [hasura/smooth-secrets-buildkite-plugin#4]
```yaml
steps:
  - command: echo "\$SECRET_FILE_PATH contains secret/env value and will be removed at the end of this build" 
    plugins:
      - hasura/smooth-secrets#v1.1.0:
          secrets:
            - strategy: aws-secrets-manager
              region: us-east-2
              key: secret/env
              path: SECRET_FILE_PATH
              type: file
```
